"""feat: add server_default in updated_at
Revision ID: 59166ecca0d0
Revises: 38c331f1b657
Create Date: 2026-06-01 23:51:46.078285
"""

from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa

# revision identifiers, used by Alembic.

revision: str = '59166ecca0d0'
down_revision: Union[str, Sequence[str], None] = '38c331f1b657'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Abrimos o modo batch para a tabela 'users'
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###